name = "api-lnmpy-com"
main = "src/index.ts"
compatibility_date = "2025-11-17"
compatibility_flags = ["nodejs_compat"]

workers_dev = false
preview_urls = false
routes = [
  { pattern = "api.lnmpy.com", custom_domain = true }
]

[[r2_buckets]]
binding = "r2_storgae"
bucket_name = "api-lnmpy-com"

[observability]
enabled = true